apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment 
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/payment:10.0.0
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef: 
              name: payment-cm 

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-cm
data:
  CART_HOST: cart-service 
  USER_HOST: user-service 
  AMQP_HOST: rabbitmq-dev.roboshopdirect.internal
  AMQP_USER: roboshop 
  AMQP_PASS: roboshop123

--- 
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080